_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 75
                - 91
                - 95
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 75
                - 91
                - 95
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.5
            "5": 0.19.8
            "6": 4.49.0
            "8":
                - 8
            "12": 0.19.8
            "13": darwin-arm64
index:
    value: nvidia-blog-embeddings
model:
    value: llama-text-embed-v2
rerank_model:
    value: cross-encoder/ms-marco-MiniLM-L-6-v2
top_k:
    value: 10
